name: Install Python and Node.js
description: Composite action to set up Python and Node.js environments and install project dependencies.

inputs:
  node-version:
    description: "The Node.js version to use."
    required: false
    default: "20.x"
  working-directory:
    description: "The directory to execute commands in."
    required: false
    default: "."
  github-token:
    description: "GitHub token for authentication."
    required: true


runs:
  using: "composite"
  steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    # Step 3: Install project dependencies
    - name: Install Node.js dependencies
      run: npm install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
