name: Angular Application Build
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: "The Node.js version to use."
        required: false
        default: "14.x"
      working-directory:
        type: string
        description: "The directory to execute commands in."
        required: false
        default: "."

jobs:
  AngularBuild:
    runs-on: self-hosted-linux-vm
    steps:
      - name: Set up Node.js
        uses: azsvcacc/github-composite-action-repo/.github/workflows/nodejs-build.yml@main
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Build Angular app
        run: npm run build
        working-directory: ${{ inputs.working-directory }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-artifacts
          path: dist
