name: Node.js Application Build

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: "The Node.js version to use."
        required: false
        default: "14.x"
      working-directory:
        type: string
        description: "The directory to execute commands in."
        required: false
        default: "."

jobs:
  NodeJs:
    runs-on: self-hosted-linux-vm
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: ./github/actions/nodejs  # Assuming the composite action is stored in ./github/actions/nodejs
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      # Step 4: Build the project
      - name: Build the project
        run: npm run build
        working-directory: ${{ inputs.working-directory }}

      # Step 5: Upload the build artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-artifacts
          path: dist
